#!/usr/bin/env python

# Copyright 2009 James Crickmere <james.crickmere@googlemail.com>
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0

"""
    Calulates files which have changed since backed up by comparing them with the
    index, and backs them up if the backup device exists.
    
    This script either runs constantly in the background or is called with 'once'
    as an argument on a regular basis.
"""

import lib_pyadis
import os, sys, threading

def start_timer():
    settings = lib_pyadis.get_settings()
    
    timer = threading.Timer(settings['scan'] * 60, do_backup)
    timer.start()


def do_backup():
    if lib_pyadis.can_backup() == True:
        settings = lib_pyadis.get_settings()
    
        for location in settings['backup_dirs']:
            real_files = lib_pyadis.scan_path(location)
            index_files = lib_pyadis.get_index_files(location)
            to_backup = lib_pyadis.compare_files(real_files, index_files)
            lib_pyadis.backup(location, to_backup)
    else:
        lib_pyadis.log("Target directory unavailable.")
    
    if len(sys.argv) == 2:
        if sys.argv[1] == 'once':
            exit()
    
    start_timer()


# Check if config file exists:
if os.path.exists(lib_pyadis.SETTINGS) == False:
    os.system('pyadis-config')
    exit()

do_backup()
